### ISSUE TITLE
Список землетрясений

### ISSUE THREAD

**Issue by Berry-More** [Vasya-Potapov/Seis-picker#3]
В настоящий момент список землетрясений выводится в виде выпадающего окна. Нужно сделать чтобы он был в небольшой по ширине колонки с постоянным положением на странице (например слева). Было бы удобно где-нибудь в этой колонке (сверху или снизу) сделать поля для ввода интервала дат (date picker или типо того), чтобы в список попадали землетрясения из этого интервала.

- [x] Список землетрясений стал иметь постоянное положение на страницу
- [x] Возможность выбирать интервал времени

**Comment by Vasya-Potapov** [comment]
Список землетрясений сейчас находиться в правом верхнем углу страницы. Добавлен DatePicker. Пространство, в котором отображается события, ограничено 300px, если все события не входят в этот предел, то есть возможность прокрутки.
